spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-gmail@gmail.com
spring.mail.password=YOUR_GMAIL_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.from=your-gmail@gmail.com

app.input-dir=./input
app.output-dir=./output
app.api.base-url=http://api.zippopotam.us/us
app.scheduler.fixed-rate-ms=120000
app.processed-extension=.processed
app.email-from=${spring.mail.from}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
